create table if not exists public.attendees (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  team text not null check (team in ('water', 'zero', 'power')),
  created_at timestamptz not null default now()
);

alter table public.attendees enable row level security;

revoke all on table public.attendees from public, anon, authenticated;
grant select on table public.attendees to anon;

drop policy if exists attendees_public_read on public.attendees;
create policy attendees_public_read
  on public.attendees
  for select
  to anon
  using (true);

create or replace function public.check_in_attendee(
  attendee_name text,
  attendee_team text
)
returns table (
  id bigint,
  name text,
  team text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  attendee_total bigint;
begin
  if attendee_name is null
    or char_length(btrim(attendee_name)) not between 1 and 120 then
    raise exception 'Attendee name must be between 1 and 120 characters.';
  end if;

  if attendee_team is null
    or attendee_team not in ('water', 'zero', 'power') then
    raise exception 'Please select a valid team.';
  end if;

  perform pg_advisory_xact_lock(42579011);

  select count(*)
  into attendee_total
  from public.attendees;

  if attendee_total >= 50 then
    raise exception 'The event has reached its 50-attendee limit.';
  end if;

  insert into public.attendees (name, team)
  values (btrim(attendee_name), attendee_team)
  returning attendees.id, attendees.name, attendees.team, attendees.created_at
  into id, name, team, created_at;

  return next;
end;
$$;

revoke all on function public.check_in_attendee(text, text) from public;
grant execute on function public.check_in_attendee(text, text) to anon;
